### ISSUE TITLE
Benchmarking Query -  Is it possible to test WebSocket connection test for 100k users? 

### ISSUE THREAD

**Issue by ketanmehta** [emqx/emqtt-bench#80]
Is it possible to test the WebSocket connection test for 100k users on single node? If yes, how?

I am wondering how the 1 million connection test per node was carried out as claimed on EMQX official site.

If the port limit of OS itself is 65536

@HJianBo

**Comment by ketanmehta** [comment]
**bump**

**Comment by ketanmehta** [comment]
@qzhuyan @emqplus @zmstone @hfeeki

**Comment by qzhuyan** [comment]
@ketanmehta 

yes, with latest version, emqtt_beach can shoot traffic from multiple interfaces with `--ifaddr`

such as 

```
--ifaddr    192.168.1.100,192.168.1.101,192.168.1.102
```
thus you could have 60k x 3  = 180K clients/users
Make sure you have these IP addrs configured on the host.

**Comment by ketanmehta** [comment]
@qzhuyan -

`Make sure you have these IP addrs configured on the host.`
Could you please elaborate further, where exactly you are pointing to configure?
Also, those nodes, they require any setup on it or how exactly they will honor request from benchmarking tool?

Little help would be greatly appreciated !

**Comment by ketanmehta** [comment]
@qzhuyan @emqplus

**Comment by qzhuyan** [comment]
@ketanmehta Sorry I missed your comments before.

what I meant is you could setup more ips on one or more network interface such like

```
# on linux, assume your network interface is eth0
# you could create three src ips as following

for i in $(seq 100 102);
do
    sudo ip addr add 192.168.100.$i dev eth0;
done

```

and then  running emqtt-bench specify with the IP addrs you created such as 

```
 --ifaddr    192.168.1.100,192.168.1.101,192.168.1.102
```

So that there are roughly 3*64k ports available for the same amount of connections.


Also, be aware that you need to fix the routing in your network as well, that the addresses you created are reachable from/to SUT (system under test).
